---
Organizations:
    - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/lean.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"

    - &Citizen
      Name: CitizenMSP
      ID: CitizenMSP
      MSPDir: crypto-config/peerOrganizations/citizen.lean.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('CitizenMSP.admin', 'CitizenMSP.peer', 'CitizenMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('CitizenMSP.admin', 'CitizenMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('CitizenMSP.admin')"

    - &Police
      Name: PoliceMSP
      ID: PoliceMSP
      MSPDir: crypto-config/peerOrganizations/police.lean.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PoliceMSP.admin', 'PoliceMSP.peer', 'PoliceMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('PoliceMSP.admin', 'PoliceMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('PoliceMSP.admin')"

    - &Forensics
      Name: ForensicsMSP
      ID: ForensicsMSP
      MSPDir: crypto-config/peerOrganizations/forensics.lean.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('ForensicsMSP.admin', 'ForensicsMSP.peer', 'ForensicsMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('ForensicsMSP.admin', 'ForensicsMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('ForensicsMSP.admin')"

    - &Court
      Name: CourtMSP
      ID: CourtMSP
      MSPDir: crypto-config/peerOrganizations/court.lean.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('CourtMSP.admin', 'CourtMSP.peer', 'CourtMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('CourtMSP.admin', 'CourtMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('CourtMSP.admin')"

    - &IdentityProvider
      Name: IdentityProviderMSP
      ID: IdentityProviderMSP
      MSPDir: crypto-config/peerOrganizations/identityprovider.lean.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('IdentityProviderMSP.admin', 'IdentityProviderMSP.peer', 'IdentityProviderMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('IdentityProviderMSP.admin', 'IdentityProviderMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('IdentityProviderMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.lean.com:7050

    BatchTimeout: 250ms
    BatchSize:
        MaxMessageCount: 50
        AbsoluteMaxBytes: 100 MB
        PreferredMaxBytes: 1 MB

    MaxChannels: 0
    EtcdRaft:
        Consenters:
            - Host: orderer0.lean.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/lean.com/orderers/orderer0.lean.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/lean.com/orderers/orderer0.lean.com/tls/server.crt

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    LEANOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Citizen
                    - *Police
                    - *Forensics
                    - *Court
                    - *IdentityProvider
    LEANChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Citizen
                - *Police
                - *Forensics
                - *Court
                - *IdentityProvider
            Capabilities:
                <<: *ApplicationCapabilities
