OrdererOrgs:
    - Name: Orderer
      Domain: lean.com
      EnableNodeOUs: true
      Template:
          Count: 1

PeerOrgs:
    - Name: Citizen
      Domain: citizen.lean.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Police
      Domain: police.lean.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Forensics
      Domain: forensics.lean.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Court
      Domain: court.lean.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: IdentityProvider
      Domain: identityprovider.lean.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1
