test:
    name: caliper_benchmark
    description: test_benchmark
    workers:
        type: local
        number: 2
    rounds:
        - label: readAsset
          description: Read Asset benchmark
          chaincodeId: evidence_cc
          txDuration: 30
          rateControl:
              type: fixed-backlog
              opts:
                  unfinished_per_client: 2
          callback: benchmarks/callbacks/readAssetBenchmarks.js
          arguments:
              assets: 10

monitor:
    type:
        - none

observer:
    type: local
    interval: 5
