test:
    name: caliper_benchmark
    description: test_benchmark
    workers:
        type: local
        number: 2
    rounds:
        - label: readAsset
          description: Read Asset benchmark
          chaincodeId: fir_cc
          txDuration: 30
          rateControl:
              type: fixed-backlog
              opts:
                  unfinished_per_client: 2
          callback: benchmarks/callbacks/readAssetBenchmark.js
          arguments:
              assets: 10

monitor:
    type:
        - docker
        - process
    docker:
        containers:
            - all
        charting:
            polar:
                metrics:
                    - all
            bar:
                metrics:
                    - Memory(max)
    process:
        processes:
            - command: node
              arguments: fabricClientWorker.js
              multiOutput: avg
        charting:
            bar:
                metrics:
                    - all

observer:
    type: local
    interval: 5
