test:
    name: caliper_benchmark
    description: test_benchmark
    workers:
        type: local
        number: 2
    rounds:
        - label: readAsset
          description: Read Asset benchmark
          chaincodeId: fir_cc
          txDuration: 120
          rateControl:
              type: fixed-backlog
              opts:
                  tps: 100
          callback: benchmarks/callbacks/readAssetBenchmark.js
          arguments:
              assets: 10
              seed: 1
        - label: createAsset
          description: Create Asset benchmark
          chaincodeId: fir_cc
          txDuration: 120
          rateControl:
              type: fixed-backlog
              opts:
                  tps: 100
          callback: benchmarks/callbacks/createAssetBenchmark.js
          arguments:
              assets: 10
        - label: queryAsset
          description: Query Asset benchmark
          chaincodeId: fir_cc
          txDuration: 120
          rateControl:
              type: fixed-backlog
              opts:
                  tps: 100
          callback: benchmarks/callbacks/queryAssetBenchmark.js
          arguments:
              assets: 10
              seed: 1

monitor:
    type:
        - docker
        - process
    docker:
        containers:
            - all
        charting:
            polar:
                metrics:
                    - all
            bar:
                metrics:
                    - Memory(max)
    process:
        processes:
            - command: node
              arguments: fabricClientWorker.js
              multiOutput: avg
        charting:
            bar:
                metrics:
                    - all

observer:
    type: local
    interval: 5
